# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('unauthorized_customer', 'Unauthorized Customer'), ('authorized_customer', 'Authorized Customer'), ('shipper', 'Shipper/Logistic Partner'), ('order_tracker', 'Orders Tracker'), ('admin', 'Admin')], default='unauthorized_customer', max_length=32),
        ),
    ]
