# Generated by Django 5.2.1 on 2025-06-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_role'),
        ('profiles', '0002_rename_timestamp_profile_created_at_and_more'),
    ]

    operations = [
    ]
