# Generated by Django 5.2.1 on 2025-06-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_merge_20250602_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
