# Generated by Django 5.2.1 on 2025-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shipper', 'Shipper/Logistic Partner'), ('order_tracker', 'Orders Tracker'), ('admin', 'Admin')], max_length=32),
        ),
    ]
