# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'permissions': [('can_view_transaction_type', 'Can view transaction type'), ('can_add_transaction_type', 'Can add transaction type'), ('can_edit_transaction_type', 'Can edit transaction type'), ('can_delete_transaction_type', 'Can delete transaction type')]},
        ),
    ]
