# Generated by Django 5.2.1 on 2025-06-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_image', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'permissions': [('can_view_product_image', 'Can view product image'), ('can_add_product_image', 'Can add product image'), ('can_edit_product_image', 'Can edit product image'), ('can_delete_product_image', 'Can delete product image')]},
        ),
    ]
