# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_method', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'permissions': [('can_view_payment_method', 'Can view payment method'), ('can_add_payment_method', 'Can add payment method'), ('can_edit_payment_method', 'Can edit payment method'), ('can_delete_payment_method', 'Can delete payment method')]},
        ),
    ]
