# Generated by Django 5.2.1 on 2025-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images', verbose_name='Product Image'),
        ),
    ]
