# Generated by Django 5.2.1 on 2025-05-27 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_remove_address_user_id_address_profile_id'),
        ('transaction_method', '0001_initial'),
        ('transaction_status', '0001_initial'),
        ('transaction_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transaction_method.paymentmethod')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transaction_status.transactionstatus')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transaction_type.transactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='transaction_user_id_4c240e_idx'), models.Index(fields=['status'], name='transaction_status__1f151a_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_6538c9_idx')],
            },
        ),
    ]
