# Generated by Django 5.2.1 on 2025-06-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcomment_user'),
        ('transactions', '00002_initial_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_transactions', to='products.product', verbose_name='Product'),
        ),
    ]
