# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_product_transaction_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'permissions': [('can_view_transaction', 'Can view transaction'), ('can_add_transaction', 'Can add transaction'), ('can_edit_transaction', 'Can edit transaction'), ('can_delete_transaction', 'Can delete transaction')], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
