# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'permissions': [('can_view_transaction_status', 'Can view transaction status'), ('can_add_transaction_status', 'Can add transaction status'), ('can_edit_transaction_status', 'Can edit transaction status'), ('can_delete_transaction_status', 'Can delete transaction status')]},
        ),
    ]
