# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_category', 'Can view category'), ('can_add_category', 'Can add category'), ('can_edit_category', 'Can edit category'), ('can_delete_category', 'Can delete category')]},
        ),
    ]
