# Generated by Django 5.2.1 on 2025-06-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '00002_initial_values'),
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
    ]
