# Generated by Django 5.2.1 on 2025-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_merge_20250602_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/categories/'),
        ),
    ]
