# Generated by Django 5.2.1 on 2025-06-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_view_cart', 'Can view cart'), ('can_add_cart', 'Can add cart'), ('can_edit_cart', 'Can edit cart'), ('can_delete_cart', 'Can delete cart')],
            },
        ),
    ]
