# Generated by Django 5.2.1 on 2025-06-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '00002_initial_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'permissions': [('can_view_product_review', 'Can view product review'), ('can_add_product_review', 'Can add product review'), ('can_edit_product_review', 'Can edit product review'), ('can_delete_product_review', 'Can delete product review')]},
        ),
    ]
