# Generated by Django 5.2.1 on 2025-06-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_specificationvalue_alter_specification_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationname',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='specificationvalue',
            old_name='name',
            new_name='value',
        ),
    ]
