# Generated by Django 5.2.1 on 2025-06-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_name_specificationname_key_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecificationValue',
            new_name='SpecificationSize',
        ),
        migrations.RenameField(
            model_name='specificationsize',
            old_name='value',
            new_name='size',
        ),
        migrations.AddField(
            model_name='specification',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.specificationsize'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
