# Generated by Django 5.2.1 on 2025-06-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_specificationvalue_specificationsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='name',
            new_name='key',
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('product', 'key', 'value', 'size')},
        ),
    ]
