# Generated by Django 5.2.1 on 2025-06-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_specificationcolor_specification_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.specificationname'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
